services:
  pg:
    image: postgres:alpine
    container_name: db
    env_file: '.env'
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    security_opt:
      - no-new-privileges:true

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - pg
    networks:
      - backend
    security_opt:
      - no-new-privileges:true

volumes:
  pg_data:

networks:
  backend:
    driver: bridge