# https://beta.ruff.rs/docs/settings/
exclude = [
    ".ide",
    ".git",
    ".venv",
    "__pycache__",
    "pg_data",
]

line-length = 120

target-version = "py312"

[format]
quote-style = "single"

[lint]
dummy-variable-rgx = "^_$"
ignore = [
    "A003",
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN102",
    "ANN401",
    "B007",
    "B008",
    "BLE001",
    "DTZ003",
    "DTZ004",
    "DTZ007",
    "EM101",
    "EM102",
    "FIX001",
    "N805",
    "PLR0913",
    "PLW2901",
    "PTH",
    "PYI024",
    "RUF002",
    "RUF003",
    "RUF012",
    "S103",
    "S105",
    "S603",
    "S607",
    "TD005",
    "TRY003",
]
# Сортировка правил как на сайте: https://beta.ruff.rs/docs/rules/
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "ANN",
    "ASYNC",
    "S",
    "BLE",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "EM",
    "EXE",
    "ISC",
    "ICN",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "INT",
    "ARG",
    "PTH",
    "TD005",
    "TD007",
    "FIX001",
    "ERA",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    "PERF",
    "RUF",
]

[lint.per-file-ignores]
"tests/*" = ["S101", "ANN001", "SLF001", "INP001", "S106", "PYI024", "DTZ001"]

[lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.isort]
combine-as-imports = true

[lint.pylint]
max-args = 10
max-returns = 8