"""initial

Revision ID: bcfd0b0c611f
Revises:
Create Date: 2025-03-28 16:41:43.140096

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'bcfd0b0c611f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
